[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.2",
    "openai>=1.108.0",
    "pydantic>=2.11.9",
    "uvicorn[standard]>=0.35.0",
]
